import type { InterventionAction } from "./intervention";

export type InterventionExecutionMode =
  | "execute"
  | "recommend"
  | "observe"
  | "unavailable";

export type InterventionCapability = {
  action: InterventionAction;

  executionMode: InterventionExecutionMode;

  supportedOnIOS: boolean;

  canExecuteAutomatically: boolean;

  canMeasureOutcome: boolean;

  explanation: string;
};

export const IOS_INTERVENTION_CAPABILITIES: Record<
  InterventionAction,
  InterventionCapability
> = {
  reduce_brightness: {
    action: "reduce_brightness",
    executionMode: "execute",
    supportedOnIOS: true,
    canExecuteAutomatically: true,
    canMeasureOutcome: true,
    explanation:
      "The app can adjust the current iOS screen brightness while respecting the platform behaviour.",
  },

  reduce_haptics: {
    action: "reduce_haptics",
    executionMode: "recommend",
    supportedOnIOS: true,
    canExecuteAutomatically: false,
    canMeasureOutcome: true,
    explanation:
      "The app can control haptic feedback that it generates, but cannot globally disable haptics generated by other apps.",
  },

  reduce_audio: {
    action: "reduce_audio",
    executionMode: "recommend",
    supportedOnIOS: true,
    canExecuteAutomatically: false,
    canMeasureOutcome: true,
    explanation:
      "The app can recommend audio reduction, but cannot generally reduce another app's audio output.",
  },

  limit_background_activity: {
    action: "limit_background_activity",
    executionMode: "recommend",
    supportedOnIOS: false,
    canExecuteAutomatically: false,
    canMeasureOutcome: false,
    explanation:
      "Third-party iOS apps cannot generally impose arbitrary background-activity limits on other apps.",
  },

  no_action: {
    action: "no_action",
    executionMode: "observe",
    supportedOnIOS: true,
    canExecuteAutomatically: true,
    canMeasureOutcome: true,
    explanation: "No intervention is applied.",
  },
};

export function getInterventionCapability(
  action: InterventionAction,
): InterventionCapability {
  return IOS_INTERVENTION_CAPABILITIES[action];
}
